version: "3.7"
volumes:
  pgdata:
services:
  postgres:
    image: dockerinaction/postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
  adminer:
    image: dockerinaction/adminer:4
    ports:
      - 8080:8080
    deploy:
      replicas: 1